### ISSUE TITLE
Building errors due to "The Type or namespace name 'AspectRatio' could not be found

### ISSUE THREAD

**Issue by Eisman111** [CantyCanadian/CantysToolbox_Objects#2]
Hello there,

hope to find you well!

I tried to build a project with your toolbox in it but the build is failing due it cannot find the following types:
- MenuITem
- AspectRatio
- MenuItemAttribute
- MenuCommand
- EditorWindow

I read that you cannot use the UnityEditor namespace in prod, how did you solved that problem? Did you move the whole toolbox into an Editor folder? 

Thanks!

**Comment by CantyCanadian** [comment]
Aaaah, yes. I'll push a fix for this issue soon-ish, but as for a temp fix for you :

- For MenuItem / MenuItemAttribute, I forgot to add it to the documentation, but the Tools' folder should be inside an Editor folder since all of the tools are meant to be editor-only. I'll make it so it's that way by default when pulling that specific repo.
- AspectRatio is more touchy. I was using Unity's provided object thinking it could be used in that way, but it's only available in-editor. That will require a proper fix that I'll push ASAP. To fix on your end, comment each lines. It shouldn't affect much if you weren't using it in the first place.
- For MenuCommand and EditorWindow, I don't know exactly where they are. If they are in the _Tools repo, then moving the repo to an Editor folder will solve it. If not, please tell me where they are.

Thanks for pointing all of these out, it allows me to make the whole toolbox better to use!

**Comment by Eisman111** [comment]
Thanks for the temp fixes and for looking into it!

**Comment by CantyCanadian** [comment]
I just committed fixes in each repos. With everything loaded in a project, I was able to make a build without errors. Sorry about that, making a build should be part of any testing methodology in the future.
